### ISSUE TITLE
Needs LICENSE file

### ISSUE THREAD

**Issue by ligi** [web3j/libp2p#1]
first of all: really great to see this project - very exciting!

But this project really needs a license file for using the project and contributing to it

**Comment by JohnChangUK** [comment]
The project is licensed under Apache 2; the license is stated in the beginning of all every file.

**Comment by ligi** [comment]
@JohnChangUK yes - but without a license file it is not picked up e.g. by github. Having a dedicated LICENSE file makes it more machine readable

**Comment by JohnChangUK** [comment]
@ligi Thank you for this, will notify our team!
